### ISSUE TITLE
KRX에서 2019-11-30 이후의 데이터를 불러오는 방법

### ISSUE THREAD

**Issue by idnotbe** [FinanceData/marcap#1]
훌륭한 라이브러리를 공개해주셔서 너무 감사드립니다.

내용이 2019-11-30 이전까지 데이터를 압축파일로 가지고 있다가 불러오는 것 같은데요.
KRX에서 원본 데이터를 내려받는 코드도 공개해주시면 안될까요?
그러면 2019-11-30일 이후의 데이터도 각자가 불러서 저장할 수 있을 것 같습니다.

감사합니다.

**Comment by FinanceData** [comment]
관심 감사합니다. 

이 리포지토리는 강의를 위한 실습과 연구용 데이터셋 공유에 목적이 있습니다. 
데이터는 현재 분기에 1회 정도는 업데이트하고 있으며, 배치 스크립트로 향후 자동으로 매일 매일 저장소를 업데이트 하도록 개선할 예정입니다.

거래소의 데이터 수집하는 코드 FinanceDataReader에 추가 할 예정입니다.
