### ISSUE TITLE
누락 데이터 관련

### ISSUE THREAD

**Issue by heejaeski** [FinanceData/marcap#10]
2021-01-22 일자 데이터가 없는 것 같습니다(다른 일자들은 확인을 못해봤습니다)
어떤 과정에서 누락된 것일까요?
업데이트가 되면 좋을 것 같습니다

라이브러리 잘 쓰고 있습니다.
감사합니다.

**Comment by kikero2** [comment]
2021-01-22,
2018-04-30,
2018-05-02,
2018-05-02 
모두 4개의 데이터만 빠져 있고, 다른 데이터는 모두 있는 것 같네요.
업데이트 되면 더 좋은 back data가 될 것 같습니다.

감사합니다.

**Comment by FinanceData** [comment]
이슈 라이징 감사합니다.
다음과 같이 데이터에 대해 확인하였고 누락 부분을 보완하였습니다.

```
from marcap import marcap_data

df = marcap_data('2021-01-22')
df = marcap_data('2018-04-30')
df = marcap_data('2018-05-02')
```

@heejaeski  님과 @kikero2  님의 상세한 리뷰 감사합니다.
