### ISSUE TITLE
2021년 4월 12일 이후로 데이터가 올라오지 않고 있네요

### ISSUE THREAD

**Issue by ewmkkpe** [FinanceData/marcap#11]
안녕하세요 잘 쓰고 있는 사람입니다. 

4월 12일 이후에 데이터가 안 올라오고 있어서 문의드립니다.

**Comment by FinanceData** [comment]
관심 감사합니다.

최근 데이터까지 업데이트 하였습니다.

github에 자동 커밋되도록 보완하였습니다. 문제가 없으면 전일 데이터까지 매일 업데이트 됩니다.
