### ISSUE TITLE
시가총액과 관련하여...

### ISSUE THREAD

**Issue by Ohhora** [FinanceData/marcap#13]
안녕하세요 잘 사용하고있어서 제공해주신 코드에 언제나 감사드립니다.

시가총액이 매일 바뀌진 않겠지만 20.12.31.까지 밖에 제공이 안되는것같아서요

혹시 가장 최근의 시가총액을 가져오려면 어떻게 해야할까요

**Comment by FinanceData** [comment]
최초에 받으실 떄는 아래와 같이 하시고,

```bash
git clone "https://github.com/FinanceData/marcap.git" marcap
```

이후에는 marcap 폴더에 가셔서
git pull 명령으로 업데이트 하시면 됩니다.

```bash
git pull 
```

데이터는 매일 업데이트 되고 있습니다. 
감사합니다.
