### ISSUE TITLE
 최신데이터는 어떻게 업데이트 하나요?

### ISSUE THREAD

**Issue by attette** [FinanceData/marcap#14]
주린이 입니다. 최신데이터는 어떻게 업데이트 하나요?
pull로 가져오라고 되어있는데, 하는 방법을 잘 모르겠습니다. 알려주심 감사하겠습니ㅏㄷ...

**Comment by hpicsk** [comment]
marcap 폴더 들어가서 git pull 명령어 실행하면 됩니다.

**Comment by FinanceData** [comment]
감사합니다. 작으나마 도움이 되시길 바랍니다.
