### ISSUE TITLE
data 매일 update 부탁드립니다.  현재는 업데이트 되어 있네요.

### ISSUE THREAD

**Issue by alforik** [FinanceData/marcap#15]
매일 데이터를 이용하려고 하는데, 지금 확인해보니 8월20일 이후 데이터 업데이트가 되지 않고 있습니다.

매일 데이터 업데이트 부탁드립니다.  매일 일자별 분석에 사용하려고 합니다.

==============

업데이트 확인했습니다.

**Comment by FinanceData** [comment]
매일 업데이트되고 있습니다. 도움이 되시길 바랍니다.
