### ISSUE TITLE
코스피 지수를 조회하는 방법이 있나요?

### ISSUE THREAD

**Issue by hpicsk** [FinanceData/marcap#16]
좋은 프레임워크를 만들어 주셔서 감사합니다.

**Comment by FinanceData** [comment]
[marcap](https://github.com/FinanceData/marcap) 은 데이터셋 입니다.

지수 등 가격 데이터가 필요하시다면 https://github.com/financedata-org/FinanceDataReader 를 참고해 보시기 바랍니다.
감사합니다.
