### ISSUE TITLE
2022년 가격데이터 칼럼(ISU_CD) 오류

### ISSUE THREAD

**Issue by oilandwater** [FinanceData/marcap#19]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/95870770/193557943-b4614047-a579-4b94-8be1-4e45809ea712.png">

marcap/data/marcap-2022.csv.gz 파일을
pd.read_csv()로 열어서 보면 'ISU_CD'라는 새로운 칼럼이 추가되어 있습니다.
2021년 데이터까지는 해당 칼럼이 없었고,  2022년 중반쯤부터 칼럼이 추가되어 있는데
오류인지 의도한 업데이트인지 확인 부탁드리겠습니다!
감사합니다

**Comment by FinanceData** [comment]
수집 상의 오류입니다. 2022-07-08 부터 ISU_CD 컬럼이 들어가고, 이 떄문에 아래와 같은 DtypeWarning 이 발생하였습니다.

```
DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False
```

해당 문제와 데이터를 FIX 하였습니다.

이슈 제기 감사합니다.
