### ISSUE TITLE
23년 데이터가 안올라오고 있습니다

### ISSUE THREAD

**Issue by ooodragon94** [FinanceData/marcap#21]
마지막 commit은 7시간 전이라 올라온줄 알았는데 안 올라왔네요 ㅠㅠ
확인 가능하실까요

**Comment by ssilb4** [comment]
@FinanceData

**Comment by FinanceData** [comment]
FIX  하였습니다 
(2023년 데이터가 아카이브 되지 않고 있었습니다)
