### ISSUE TITLE
2023년 데이터를 부탁드립니다.

### ISSUE THREAD

**Issue by boulderphd** [FinanceData/marcap#22]
안녕하세요.  marcap 수고에 늘 감사드립니다.

2023년 데이터가 올라오지 않아서 문의드립니다. 

가능하시면 2023년 데이터도 예전처럼 매일 올려주시면 감사하겠습니다.

**Comment by FinanceData** [comment]
FIX 하였습니다
(2023년 데이터가 아카이브 되지 않고 있었습니다)

**Comment by boulderphd** [comment]
감사합니다. 2023년도 데이타를 확인했습니다.
