### ISSUE TITLE
상장주식수 데이터 오류

### ISSUE THREAD

**Issue by stat17-hb** [FinanceData/marcap#5]
`marcap_data('2021-01-21', code='005930')`

로 조회했을때 상장주식수('Stocks')가 1,674,815,254로 나옵니다.

시가총액/종가 = 2211209788500/88100 = 5,969,782,550 로 계산하면 맞게 나오는데 Stocks 칼럼에 값이 잘못 들어가는 것 같습니다.

**Comment by FinanceData** [comment]
관심과 제안 감사합니다. 다음과 같이 문제가 없음을 확인하였습니다.
<img src="https://i.imgur.com/B86VIHr.png" >

결과를 어떻게  생성하셨는지 알려주시면 문제를 찾는데 도움이 되겠습니다.

**Comment by FinanceData** [comment]
1/18 기준으로 한국거래소 사이트의 변경이 있었습니다. 변경을 반영하여 데이터를 완전히 재구축하였습니다. 또한, 매일 자동으로 추가 업데이트 됩니다. 참고하시고 혹시 문제나 궁금한점 있으시면 다시 이슈 부탁 드립니다.

감사합니다.
