### ISSUE TITLE
marcap으로 수정주가 구하기

### ISSUE THREAD

**Issue by kwang-yong-hyun** [FinanceData/marcap#9]
튜토리얼에 있는데로 수정주가 구해봤는데

Financedatareader의 수정주가와는 다릅니다.

혹시 marcap 데이터로 financedatareader와 같은 수정주가를 구할 수는 없을까요??

**Comment by FinanceData** [comment]
차이가 있을 수 밖에 없습니다

거래소의 시가총액 데이터는 수정가격을 제공하지 않습니다.
marcap의 튜토리얼의 수정주가는 단순히 발생주식수에 대해서만 구합니다. 배당 등의 이벤트는 고려되어 있지 않습니다.
이런 이벤트 데이터를 모두 반영하여 계산하여 제공하기에는 저희 리소스가 많이 부족합니다 --;

marcap는 전 일자에대해 데이터를 제공하므로 오랜 기간에 대한 백테스트 등에 사용하시면 좋을 듯 합니다.

FinanceDataReader 의 데이터는 데이터 제공업체가 제공하는 수정주가입니다. 데이터 제공업체가 다양한 방식과 여러 이벤트를 반영하여 계산합니다 (국내 가격데이터는 네이버 파이낸스에서 가져오며 이 데이터의 제공자는 FnGuide 입니다)

참고가 되셨길 바랍니다.
감사합니다.
